services:
  back:
    build: ./back
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  front:
    build: ./front
    ports:
      - "8090:80"
    depends_on:
      - back