apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: weather-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#            initialDelaySeconds: 60
#            periodSeconds: 15
#            failureThreshold: 5
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
